// Official Kannur District High School List (All Kerala State Syllabus Schools, codes removed)
export const KANNUR_DISTRICT_SCHOOLS: string[] = [
  "A K A S G V H S S Payyanur",
  "A K G S Govt. H. S. S. Peralasseri",
  "A.K.S.G.H.S. Malappatam",
  "A.K.S.G.H.S. Malappattam",
  "AKASGVHSS Payyannur, Payyannur PO Kannur 670307",
  "AKG Govt.Higher Secondary School Pinarayi",
  "AKG Memorial English High School, Kannur",
  "AKGM GOVT HSS, PINARAYI, KANNUR",
  "AKGS GHSS, PERALASSERY, KANNUR",
  "AL-FALAH High School Peringadi",
  "Anjarakandy Higher Secondary School",
  "ANJARAKANDY HSS, ANJARAKANDY, KANNUR",
  "AVS Govt.Higher Secondary School Karivellur",
  "Azhikode H S S",
  "Azhikode Higher Secondary School",
  "B E M P High School Thalassery",
  "BAKHITHA ENGLISH MEDIUM High  SCHOOL CHERUKUNNU",
  "Bright English School, Thalassery",
  "BVJMHS Perumbadavu",
  "C H M H S Kavumpady",
  "C H Muhammed Koya Memorial H S S, Kavumpady",
  "C.H.M.H.S.S.Elayavoor",
  "CHAPPARAPADAVU HIGH SCHOOL",
  "Chavara Special High School.Iritty",
  "CHEMBILODE HIGHER SECONDARY SCHOOL, THALAVIL",
  "Chembilode HSS",
  "Cherupushpa HS Chanadanakampara",
  "CHM Higher Secondary School, Elayavoor",
  "CHMHS Kavumpady",
  "CHMKM Higher Secondary School Vadakkumbad Ramanthally",
  "CHMKS GOVT HSS, MATTOOL, KANNUR",
  "CHMKSGHSS MATTUL",
  "CHMKSGHSS VALAPATTANAM",
  "CHOTHAVOOR HS. CHAMPAD",
  "Chovva H.S.S.Chovva",
  "D I SABHA GIRLS HSS, KANNUR, KANNUR",
  "D.I.S.E.M.H.S.S.Kannur",
  "D.I.S.Girls H.S.S.Kannur",
  "DARUL HASANATH EMHS KANNADIPARAMBA",
  "Devamatha High School Paisakkary",
  "DON BOSCO SPEECH AND HEARING SCHOOL KARAKUNDU",
  "E M S Smaraka Govt H S S Pappinisseri",
  "Falah English Medium H S Narath",
  "G H S Rayarome",
  "G H S S Manathana",
  "G H S S SREEPURAM",
  "G H S Thavidissery",
  "G R F T V H S S  Azhikkal",
  "G W H S S CHERUKUNNU",
  "G.H.S. Koyyam",
  "G.H.S. Nedungome",
  "G.H.S. S. Chuzhali",
  "G.H.S.S. Irikkur",
  "G.H.S.S. Sreekandapuram",
  "GBHSS  CHERUKUNNU",
  "GBVHSS MADAYI",
  "GGHSS MADAYI",
  "GGHSS, THIRUVANGAD, THALASSERY, KANNUR",
  "GGVHSS Cherukunnu, Cherukunnu.P.O. Kannur 670301",
  "GHS Kottayam Malabar",
  "GHS Kuttiyeri",
  "GHS Pacheni",
  "GHS PATTUVAM",
  "GHSS Aralam",
  "GHSS AZHIKKODE, AZHIKKODE, KANNUR",
  "GHSS Chavassery",
  "GHSS CHERUTHAZHAM",
  "GHSS Chittariparamaba",
  "GHSS KADANNAPPALLY",
  "GHSS KANIYANCHAL",
  "GHSS KAVUMBHAGAM",
  "GHSS KOTTILA",
  "GHSS KUNHIMANGALAM",
  "GHSS Kuthuparamba",
  "GHSS Malur",
  "GHSS Mambaram",
  "GHSS Manathana",
  "GHSS Pala",
  "GHSS Pattiam",
  "GHSS SREEPURAM",
  "GHSS Vengad",
  "GHSS, CHERUKUNNU, KANNUR",
  "GHSSPala",
  "Govt H S Kalikkadava",
  "Govt H S S  Azhikode",
  "Govt H S S Ulikkal,Kannur",
  "GOVT HIGH SCHOOL ARALAM FARM",
  "Govt Higher Secondary School, Aroli, Papinassery",
  "GOVT HSS FOR BOYS, MADAI, KANNUR",
  "GOVT HSS, CHALA, KANNUR",
  "GOVT HSS, CHELORA, KANNUR",
  "GOVT HSS, CHITTARIPPARAMBA, KANNUR",
  "GOVT HSS, KOZHICHAL, KANNUR",
  "GOVT HSS, MORAZHA, KANNUR",
  "GOVT HSS, MUZHAPPILANGAD, KANNUR",
  "GOVT HSS, PALA, KANNUR",
  "GOVT HSS, PALLIKKUNNU, KANNUR",
  "GOVT TOWN HSS, KANNUR, KANNUR",
  "Govt:VHSS for Girls Kannur, Payyambalam 670001",
  "GOVT. GIRLS HSS, PAYYANNUR, KANNUR",
  "Govt. H S S Chattukapara",
  "Govt. H S S Chelora",
  "Govt. H S S Muzhappilangad",
  "Govt. H S S Palayad",
  "Govt. H S S Pallikkunnu",
  "Govt. H S S Vadakkumpad",
  "Govt. H.S.S Chundangapoil",
  "Govt. H.S.S. Munderi",
  "Govt. High School Thirumeni",
  "Govt. High School, Cheriyoor",
  "Govt. High School, Kuttiyeri",
  "Govt. High School, Pacheni",
  "GOVT. HIGH SCHOOL, PADIYOOR",
  "Govt. High School, Perinkari",
  "Govt. Higher Secondary School Korome",
  "Govt. Higher Secondary School Mathamangalam",
  "Govt. Higher Secondary School Mathil",
  "Govt. Higher Secondary School Prappoil",
  "Govt. Higher Secondary School Ramanthally",
  "Govt. Higher Secondary School Thottada",
  "Govt. Higher Secondary School Vellur",
  "GOVT. HSS, CHIRAKKARA, THALASSERY, KANNUR",
  "GOVT. HSS, KANNADIPPARAMBA, KANNUR",
  "GOVT. HSS, MAMBRAM, AYITHARA MAMBARAM (PO), KUTHUPARAMBA - 670643",
  "GOVT. HSS, PUZHATHI, KANNUR",
  "Govt. V H S S Karthikapuram",
  "Govt. VHSS Kadirur",
  "GOVT. VHSS, EDAYANUR, KANNUR",
  "Govt.Brennen HSS Thalassery",
  "Govt.City H.S.S.Kannur",
  "Govt.Girls Higher Secondary School Payyannur",
  "Govt.H S S Kannadiparamba",
  "Govt.H.S.S. Chala",
  "Govt.High School Aroli",
  "Govt.High School Morazha",
  "Govt.High School Puzhathi",
  "Govt.Higher Secondary School Ettikulam",
  "Govt.Higher Secondary School Kozhichal",
  "Govt.Higher Secondary School Peringome",
  "Govt.Higher Secondary School Thirumeni",
  "Govt.Higher Secondary School Vayakkara",
  "Govt.HSS Thiruvangad",
  "GOVT.MODEL RESIDENTIAL SCHOOL KANNUR",
  "Govt.THS-VHSS Neruvambram, Payangadi P.O Kannur 670303",
  "Govt.Town H.S.S.Kannur",
  "GOVT.TOWN HIGHER SECONDARY SCHOOL THALASSERY",
  "Govt.V.H.S.S Pulingome",
  "Govt.V.H.S.S.For Girls Kannur",
  "Govt.V.H.S.S.Kannur",
  "Govt.VHSS Kurumathur",
  "Govt.Vocational H S S Chirakkara",
  "Govt.Vocational H S S Koduvally",
  "GRFT VHSS Azheekal Kannur",
  "GVHSS CHERUKUNNU",
  "GVHSS Chirakkara.P.O Chirakkara 670104",
  "GVHSS Edayannur",
  "GVHSS Edayannur, Edyannur.P.O Kannur 670595",
  "GVHSS Kadirur, Kadirur.P.O Thalassery Kannur 670642",
  "GVHSS Koduvally, Thalassery Kannur 670101",
  "GVHSS KURMATHUR",
  "GVHSS Kurumathur, Kurumathur.P.O Kannur 670142",
  "GVHSS Madayi, Payangadi.P.O Kannur 670303",
  "GVHSS, KATHIRUR, KANNUR",
  "GWHSS CHERUKUNNU",
  "Hidayat EMHS,Pappinisseri",
  "IJMHSS Kottiyoor",
  "IMNS GOVT HSS, MAYYIL, KANNUR",
  "IMNS Govt. High School Mayyil",
  "Irikkur Rahmaniya Orphanage HS",
  "Iritty High School",
  "JAMA-ATH HS PUTHIYANGADI",
  "K K N P M G V H S S PARIYARAM",
  "K K V MEMORIAL PANOOR H S S",
  "K P C H S S Pattannur",
  "K P R G S G H S S Kalliasseri",
  "Kadachira High School",
  "Kadachira Higher Secondary School",
  "Kadambur Higher Secondary School",
  "KADAMBUR HSS, EDAKKAD, KANNUR",
  "Kadavathur VHSS",
  "Kambil Mopla High School",
  "Kambil Mopla Higher Secondary school",
  "KARAKKUND DON-BOSCO SPEECH & HEARING HSS, PARIYARAM",
  "KARIYAD NAMBIAR'S H S",
  "Kariyad Nambiars Higher Secondary School, Kariyad",
  "KARUNYANIKETHAN FOR THE DEAF VILAYANKODE",
  "Khaide Millath Memorial HS Kavvayi",
  "KKV MEMORIAL HSS, PANOOR, PANOOR P.O., KANNUR",
  "Koodali Higher Secondary School",
  "Koodali HSS",
  "KOOTHUPARAMBA HSS, KOOTHUPARAMBA, KANNUR",
  "Kottayam Raja`s H S Pathiriyad",
  "KPCHSS Pattannur",
  "KPR Gopalan Smaraka G VHSS Kalliassery Kannur 670562",
  "KPRGS GOVT HSS, KALLIASSERY, KANNUR",
  "Kuthuparamba H S S",
  "Little Flower E.M. H.S. Kelakam",
  "M M H S New Mahe",
  "M M H S S Thalassery",
  "Mambaram HSS",
  "Mary Queen`s High School Kudianmala",
  "MARYGIRI HS THERTHALLY",
  "Maryland High School Madampam",
  "Mattannur HSS",
  "MECA PAZHAYANGADI",
  "MEDICAL COLLEGE PUBLIC SCHOOL Pariyaram",
  "MM Higher Secondary School, New Mahe",
  "MODEL RESIDENTIAL SCHOOL, PATTUVAM, KANNUR, NEC",
  "MOOTHEDATH H S TALIPARAMBA",
  "NADUVIL H S",
  "Naduvil Higher Secondary School",
  "NAJATH GIRLS HS MATTUL",
  "NAM MEMORIAL HSS, PERINGATHUR, KANNUR",
  "NAMHSS PERINGATHUR",
  "Nirmala Higher Secondary School Chemperi",
  "NSS HSS ALAKODE",
  "Oniyan High School Kotiyeri",
  "P .R MEMORIAL KOLAVALLUR H S S",
  "P.R.M. KOLAVALLOOR HSS, THUVAKKUNNU, KANNUR - 670693",
  "PANCHAYATH HSS, PAPPINISSERY, KANNUR",
  "Parassinikadavu Higher Secondary  School",
  "Pattiam Gopalan Memorial Govt. H S S Cheruvanchery",
  "PKMHSS KADAVATHUR",
  "PR MEMORIAL HSS, PANOOR, PANOOR P.O., KANNUR",
  "PRM HSS PANOOR",
  "RAHMANIYA HS MUTTAM",
  "Raja's HSS, CHIRAKKAL",
  "Rajeev Gandhi Memorial HSS, Mokeri",
  "RAJEEVGANDHI MEMORIAL H S S MOKERI",
  "RAMAKRISHNA HS. OLAVILAM",
  "RAMAVILASAM HSS. CHOKLI",
  "RAMAVILASOM HSS, CHOKLI, KANNUR",
  "Ranijai H S Nirmalagiri",
  "S A B T M High School Thayineri",
  "S N Trust H S S Thottada",
  "SABTM High School Thayineri",
  "Sacred Heart Girls H S Thalassery",
  "Sacred Heart High School Payyavoor",
  "Sacred Heart HS Angadikadavu",
  "Sacred Heart HSS Angadikadavu",
  "Santhome H S S Kolakkad",
  "SANTHOME HSS, KOLAKKAD, KOLAKKAD P.O., KANNUR",
  "SEETHI SAHIB H S S TALIPARAMBA",
  "SEETHI SAHIB HSS, THALIPARAMBA, KANNUR",
  "SHENOY SMARAKA GOVT HIGHER SECONDARY SCHOOL PAYYANUR",
  "SIR SYED HIGH SCHOOL TALIPARAMBA",
  "Sivapuram H S",
  "Sivapuram H S S",
  "SN TRUST HSS, THOTTADA, KANNUR",
  "ST JOSEPH'S H S S VAYATTUPARAMBA",
  "ST JOSEPH'S HS PULIKURUMBA",
  "St Joseph's School,Peratta",
  "ST JOSEPH`S H S PUSHPAGIRI",
  "ST MARYS ENGLISH MEDIUM HIGH SCHOOL NADUVIL",
  "ST MARYS HSS, EDOOR, PAYAM P.O., KANNUR",
  "ST. Cornelius Higher Secondary School, Kolayad. P.O, Chittariparamba",
  "ST. JOSEPH S HSS, THALASSERY, KANNUR",
  "St. Mary's High School, Cherupuzha",
  "St. Teresa's A.I.H.S.S, Kannur",
  "St.Augustine High School Nellikkutty",
  "St.Cornelius HS Kolayad",
  "St.George High School Chempanthotty",
  "St.John Baptist E.M.HSS Kadathumkadavu",
  "St.Joseph HSS.peravur",
  "St.Joseph's HSS Thalassery",
  "St.Joseph`s English School Cherupuzha",
  "St.Josephs HS Adakkathode",
  "St.Josephs HS Kunnoth",
  "St.Josephs HS Peravoor",
  "St.Mary's High School For Girls, Payyannur",
  "St.Marys HSS Edoor",
  "St.Michael's A.I.H.S.S.Kannur",
  "St.Sebastians H s s Velimanam",
  "St.Sebastians Hss Velimanam",
  "St.Thomas H.S Kelakam",
  "St.Thomas High School Manikkadave",
  "St.Thomas HS Karikkottakkary",
  "St.Thomas HS Kiliyanthara",
  "Tagore Memorial Higher Secondary  School Vellora",
  "TAGORE MEMORIAL HSS, VELLORA, KANNUR",
  "Tagore Vidyaniketan GVHSS Thaliparamba, Rabeendrapuram.P.O 670141",
  "TAGORE VIDYANIKETHAN GOVT H S S",
  "TECHNICAL H S KANNUR",
  "TECHNICAL H S NERUVAMBRAM",
  "TECHNICAL HS KANNUR",
  "TECHNICAL HS NADUVIL",
  "THADIKKADAVU G H S",
  "Thajul uloom EMHS Valapattanam",
  "V P ORIENTAL HS. CHOKLI",
  "V.M.M. English Medium School, Palottupally",
  "WADIHUDA HS PAYANGADI"
];

// Alias for backward compatibility
export const POPULAR_SCHOOLS = KANNUR_DISTRICT_SCHOOLS;
