export const POPULAR_SCHOOLS = [
  "Govt Model Higher Secondary School, Thiruvananthapuram",
  "Govt Girls Higher Secondary School, Pattom, Thiruvananthapuram",
  "St. Joseph's Boys' Higher Secondary School, Kozhikode",
  "Kendriya Vidyalaya, Pattom, Thiruvananthapuram",
  "Kendriya Vidyalaya, Ernakulam",
  "Sacred Heart Higher Secondary School, Thevara, Kochi",
  "St. Thomas Residential School, Mukkolakkal, Thiruvananthapuram",
  "BMM English Medium Senior Secondary School, Kottayam",
  "Govt Ganapath Boys Higher Secondary School, Chalappuram, Kozhikode",
  "Chinmaya Vidyalaya, Vaduthala, Kochi",
  "Govt City Higher Secondary School, Kannur",
  "St. Mary's Higher Secondary School, Pattom, Thiruvananthapuram",
  "Vidyodaya School, Thevakkal, Kochi",
  "Govt Higher Secondary School, Medical College Campus, Kozhikode",
  "Jawahar Navodaya Vidyalaya, Chettikulangara, Alappuzha",
  "St. Antony's Higher Secondary School, Kacheripady, Ernakulam",
  "Govt Sanskrit Higher Secondary School, Tripunithura",
  "Nirmala Higher Secondary School, Muvattupuzha",
  "Choice School, Thripunithura, Kochi",
  "Bharatiya Vidya Bhavan, Chevayur, Kozhikode",
  "Govt Higher Secondary School, Karaparamba, Kozhikode",
  "Loyola School, Sreekariyam, Thiruvananthapuram",
  "St. Teresa's Convent Girls HSS, Ernakulam",
  "Govt Boys Higher Secondary School, Manjeri, Malappuram",
  "Govt Higher Secondary School, Cheruvannur, Kozhikode",
  "St. Michael's Anglo-Indian Higher Secondary School, Kannur",
  "Govt Victoria Higher Secondary School, Palakkad",
  "St. Aloysius Higher Secondary School, Kollam",
  "Govt Boys Higher Secondary School, Attingal",
  "St. Albert's Higher Secondary School, Ernakulam",
];
